name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install dependencies
        run: npm install

      - name: Make distributables (Mac arm64)
        if: matrix.os == 'macos-latest'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_CONTENT: ${{  secrets.CSC_CONTENT }}
          CSC_CONTENT_PASSWORD: ${{ CSC_KEY_PASSWORD  }}
        run: npm run make -- --arch=arm64

      - name: Make distributables (Mac x64)
        if: matrix.os == 'macos-latest'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: npm run make -- --arch=x64

      - name: Make distributables (Windows and Linux)
        if: matrix.os != 'macos-latest'
        run: npm run make
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/make/**/*
