name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    strategy:
      # matrix:
      #   os: [macos-latest, windows-latest, ubuntu-latest]
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-latest
            arch: x64
          - os: windows-latest
          - os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Import signing certificate
        if: matrix.os == 'macos-latest'
        env:
          CSC_LINK: ${{ secrets.CSC_CONTENT }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: |
          echo "$CSC_LINK" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CSC_KEY_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          
          echo "Signing identities found:"
          security find-identity -v -p codesigning build.keychain

          echo "App bundles found:"
          find . -name "*.app"
      
      - name: Build macOS
        if: matrix.os == 'macos-latest'
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_CONTENT }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: |
          npm install
          npm run make -- --arch=${{ matrix.arch }}


      - name: Install dependencies
        if: matrix.os != 'macos-latest'
        run: npm install
      - name: Make distributables (Windows and Linux)
        if: matrix.os != 'macos-latest'
        run: npm run make -- --verbose

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/make/**/*