name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install dependencies
        run: npm install

      - name: Make distributables (Mac)
        if: matrix.os == 'macos-latest'
        run: npm run make -- --arch=universal

      - name: Make distributables (Windows and Linux)
        if: matrix.os != 'macos-latest'
        run: npm run make

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/make/**/*
